export const data = {
  users: [
    {
      id: 1,
      name: "الما نریمانی",
      username: "elma",
      email: "elma@gmail.com",
      password: "elma0101",
    },
    {
      id: 2,
      name: "مینا عابدی",
      username: "mina",
      email: "mina@gmail.com",
      password: "mina0101",
    },
    {
      id: 3,
      name: "پیمان احمدی",
      username: "peyman",
      email: "peyman12@gmail.com",
      password: "Ahmadi0101",
    },
    {
      id: 4,
      name: "سینا اسدی",
      username: "sina",
      email: "sina@gmail.com",
      password: "sina0101",
    },
    {
      id: 5,
      name: "عاطفه صمدی",
      username: "atefeh",
      email: "atefeh@gmail.com",
      password: "atefeh0101",
    },
    {
      id: 6,
      name: "هانیه قربانی",
      username: "haniyeh",
      email: "haniyeh@gmail.com",
      password: "haniyeh0101",
    },
    {
      id: 7,
      name: "علی عالمی",
      username: "ali",
      email: "ali@gmail.com",
      password: "ali0101",
    },
    {
      id: 8,
      name: "مهتاب سهرابی",
      username: "mahtab",
      email: "mahtab@gmail.com",
      password: "mahtab0101",
    },
    {
      id: 9,
      name: "امیر محمودی",
      username: "amir",
      email: "amir@gmail.com",
      password: "amir0101",
    },
  ],
  products: [
    {
      id: 1,
      title: "کفش ورزشی",
      price: 8_000_000,
      slug: "kafsh-a1",
    },
    {
      id: 2,
      title: "کیف ورزشی",
      price: 3_000_000,
      slug: "kif-a1",
    },
    {
      id: 3,
      title: "شلوار ورزشی",
      price: 5_000_000,
      slug: "shalvar-a1",
    },
    {
      id: 4,
      title: "کاپشن ورزشی",
      price: 8_000_000,
      slug: "kapshan-a1",
    },
    {
      id: 5,
      title: "مانتو",
      price: 1_000_000,
      slug: "manto-a1",
    },
    {
      id: 6,
      title: "شلوارلی",
      price: 2_000_000,
      slug: "shalvarli-a1",
    },
    {
      id: 7,
      title: "شال",
      price: 500_000,
      slug: "shal-a1",
    },
    {
      id: 8,
      title: "کلاه ورزشی",
      price: 300_000,
      slug: "kolah-a1",
    },
    {
      id: 9,
      title: "لپ تاپ",
      price: 120_000_000,
      slug: "jorab-a1",
    },
    {
      id: 10,
      title: "عینک",
      price: 4_000_000,
      slug: "einak-a1",
    },
    {
      id: 11,
      title: "کوله پشتی",
      price: 2_500_000,
      slug: "koleh-a1",
    },
    {
      id: 12,
      title: "تیشرت",
      price: 600_000,
      slug: "tishert-a1",
    },
  ],
};

